version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_DATABASE: aws_metadata
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,secretsmanager,rds
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql_data:
